language: scala

jdk: openjdk8

scala:
   - 2.10.4
   - 2.12.10

script:
   - echo BURP_SCAN_URL = http://localhost >> temp.log &&
     sbt compile test run >> temp.log

after_success:   
   - java -jar burp-ci-driver-1.0.7beta.jar temp.log
     

notifications:
  email: mgotur@xtivia.com