language: scala

jdk: openjdk8

scala:
   - 2.10.4
   - 2.12.10

script:
   - sbt compile test run

after_success:   
   - java -jar burp-ci-driver-1.0.7beta.jar

notifications:
  email: mgotur@xtivia.com