language: scala

jdk: openjdk8

scala:
   - 2.10.4
   - 2.12.10

script:
   - echo BURP_SCAN_URL = https://dashboard.sandbox53.localytics.com >> temp.log &&
     sbt compile test run >> temp.log

after_success:  
   - |
     while sleep 9m; do
       echo "====[ $SECONDS seconds still running ]===="
     done &
     bash ./burp-scanner.sh >> temp_burp.log &&
     less temp_burp.log

notifications:
  email: mgotur@xtivia.com