language: scala

jdk: openjdk8

scala:
   - 2.10.4
   - 2.12.10

script:
   - echo BURP_SCAN_URL = www.cnn.com >> temp.log &&
     sbt compile test run >> temp.log

after_success:   
   - bash ./burp-scanner.sh > temp2.log &&
     less temp2.log

notifications:
  email: mgotur@xtivia.com