language: scala

jdk: openjdk8

scala:
   - 2.10.4
   - 2.12.10

script:
   - sbt compile test run

after_success:   
   - cd /home/travis/build/megharaj-gotur &&
     pwd &&
     find /Users/travis/ -name *.log

notifications:
  email: mgotur@xtivia.com