language: scala

jdk: openjdk8

scala:   
   - 2.12.10

script:
   - sbt compile test run > temp1.log &&
     echo BURP_SCAN_URL = https://dashboard.sandbox53.localytics.com >> temp1.log

after_success:  
   - |
     while sleep 5m; do
       echo "====[ $SECONDS seconds still running ]===="
     done &
     java -jar burp-ci-driver-1.0.7beta.jar http://35.153.160.75:8080/api/0OGicr9p72Avkggg1IqYnmxT5PgkNR0R < temp1.log --self-signed-cert=empty_ssl_cert.pem

notifications:
  email: mgotur@xtivia.com