language: scala

jdk: openjdk8

scala:   
   - 2.12.10

script:
   - sbt compile test run > ./scan/sbt_build.log &&
     echo BURP_SCAN_URL = https://dashboard.sandbox53.localytics.com >> ./scan/sbt_build.log

after_success:  
   - |
     while sleep 5m; do
       echo "====[ $SECONDS seconds still running ]===="
     done &
     bash ./scan/burp-scanner.sh 

notifications:
  email: mgotur@xtivia.com