language: scala

jdk: openjdk8

scala:
   - 2.10.4
   - 2.12.10

script:
   - sbt compile test run

after_success:   
   - bash <(cd /home/travis/build/megharaj-gotur/burp-testing/project; ls -lrt)

notifications:
  email: mgotur@xtivia.com