language: scala

jdk: openjdk8

scala:   
   - 2.12.10

script:
   - sbt compile test run > ./scan/temp1.log &&
     echo BURP_SCAN_URL = https://dashboard.sandbox53.localytics.com >> ./scan/temp1.log

after_success:  
   - cd scan 
   - ls -lrt 

notifications:
  email: mgotur@xtivia.com