language: scala

jdk: openjdk8

scala:
   - 2.10.4
   - 2.12.10

script:
   - echo BURP_SCAN_URL = https://www.localytics.com/product-demo-signup/ >> temp.log &&
     sbt compile test run >> temp.log

after_success:  
   - |
     while sleep 9m; do
       echo "====[ $SECONDS seconds still running ]===="
     done &
     java -jar burp-ci-driver-1.0.7beta.jar http://35.153.160.75:8080/api/kGOvDZuqUsK2k19wRpkEfJ0y8JadQF7L < temp.log --self-signed-cert=empty_ssl_cert.pem

notifications:
  email: mgotur@xtivia.com